name: Generate requirement.txt
on: [push, pull_request]
jobs:
  gen-requirement:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          architecture: "x64"
      - name: Display Python version
        run: python --version
      - name: Install packages
        run: pip install pipreqs
      - name: Generate pip requirements
        run: |
          pipreqs . --force

