from .LinearLayer.LinearLayer import LinearLayer
from .SCINet.SCINet import SCINet
from .MTGNN.MTGNN import MTGNN
from .RNN.RNN import RNN
#from .InceptionTime.InceptionTime import InceptionTime
#from .TransformerModel.TransformerModel import TransformerModel
from .STGCN.STGCN import STGCN
from .Seq2Seq.Seq2Seq import Seq2Seq
from .FNN.FNN import FNN
from .DCRNN.DCRNN import DCRNN
from .AutoEncoder.AutoEncoder import AutoEncoder
from .GWNET.GWNET import GWNET
#from .STMGAT.STMGAT import STMGAT
#from .Autoformer.Autoformer import Autoformer
#from .Transformer.Transformer import Transformer
from .TGCN.TGCN import TGCN
#from .MLP.MLP import MLP
#from .gMLP.gMLP import gMLP
#from .FCN.FCN import FCN
#from .ResNet.ResNet import ResNet
#from .ResCNN.ResCNN import ResCNN
#from .TCN.TCN import TCN
#from .OmniScaleCNN.OmniScaleCNN import OmniScaleCNN
#from .XCM.XCM import XCM
#from .ATDM.ATDM import ATDM
#from .HGCN.HGCN import HGCN
